export interface Pokemon {
    id: string,
    name: string,
    supertype: string,
    subtype: string[],
    level: string,
    hp: string,
    type: string[],
    rules: object[],
    ancientTrait: object,
    abilities: object[],
    attacks: object[],
    weaknesses: object[],
    resistances: object[],
    retreatCost: string[],
    convertedRetreatCost: number,
    set: object,
    number: string,
    artist: string,
    rarity: string,
    flavorText: string,
    nationalPokedexNumbers: number[],
    legalities: object,
    regulationMark: string,
    images: any,
    tcgplayer: object,
    cardmarker: object
}